def goToHackingtons () :
  print ("go left at the stop sign")
  print ("stop at the light")
  print ("Pull into the parking lot")

goToHackingtons()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()
goToHackingtons ()